#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for fast-ta Micro-Experiments

set -e

echo "========================================"
echo "Starting Development Environment"
echo "fast-ta Micro-Experiments"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Rust installation
if ! command -v rustc &> /dev/null; then
    echo -e "${RED}Rust not found. Installing...${NC}"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
else
    echo -e "${GREEN}✓ Rust found: $(rustc --version)${NC}"
fi

# Check MSRV
RUST_VERSION=$(rustc --version | cut -d' ' -f2)
REQUIRED_VERSION="1.75"
if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$RUST_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo -e "${RED}Rust version $RUST_VERSION is below MSRV $REQUIRED_VERSION${NC}"
    echo "Please update Rust: rustup update"
    exit 1
fi
echo -e "${GREEN}✓ Rust version meets MSRV 1.75${NC}"

# Check cargo-tarpaulin for coverage
if ! command -v cargo-tarpaulin &> /dev/null; then
    echo -e "${YELLOW}Installing cargo-tarpaulin for coverage analysis...${NC}"
    cargo install cargo-tarpaulin
else
    echo -e "${GREEN}✓ cargo-tarpaulin found${NC}"
fi

# ============================================
# CREATE DIRECTORY STRUCTURE
# ============================================

echo ""
echo "Creating project structure..."

# Create crate directories
mkdir -p crates/fast-ta-core/src/{indicators,kernels,plan}
mkdir -p crates/fast-ta-experiments/src
mkdir -p crates/fast-ta-experiments/benches/common

# Create experiment report directories
mkdir -p benches/experiments/{E01_baseline,E02_running_stat,E03_ema_fusion,E04_rolling_extrema,E05_plan_overhead,E06_memory_writes,E07_end_to_end}

# Create docs directories
mkdir -p docs/{decisions,experiments}

echo -e "${GREEN}✓ Directory structure created${NC}"

# ============================================
# BUILD WORKSPACE
# ============================================

echo ""
echo "Building workspace..."

if cargo build --workspace; then
    echo -e "${GREEN}✓ Workspace built successfully${NC}"
else
    echo -e "${RED}✗ Workspace build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running tests..."

if cargo test --workspace; then
    echo -e "${GREEN}✓ All tests passed${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed (expected in initial setup)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project Structure:"
echo "  - fast-ta-core: ./crates/fast-ta-core"
echo "  - fast-ta-experiments: ./crates/fast-ta-experiments"
echo ""
echo "Common Commands:"
echo "  Build workspace:    cargo build --workspace"
echo "  Run tests:          cargo test --workspace"
echo "  Run benchmarks:     cargo bench --workspace"
echo "  Check coverage:     cargo tarpaulin --workspace --out Html"
echo "  Lint code:          cargo clippy --workspace -- -D warnings"
echo "  Format code:        cargo fmt --workspace"
echo ""
echo "Benchmark outputs:"
echo "  - HTML Reports:     ./target/criterion/report/index.html"
echo "  - Experiment Reports: ./benches/experiments/EXX/REPORT.md"
echo ""
echo "Next Steps:"
echo "  1. Implement Phase 0: Foundation & Benchmarking Infrastructure"
echo "  2. Follow implementation_plan.json for subtask order"
echo "  3. Run tests after each subtask completion"
echo ""
